version: "3"

services:
  
  nginx:
    image: nginx
    volumes:
    - ./nginx/chat.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
    - "80:80"
    depends_on:
    - app

  app:
    image: node:6
    working_dir: /usr/app
    volumes:
    - ./:/usr/app
    - ./views/:/usr/app/views
    - /usr/app/node_modules
    command: npm run deploy
    depends_on:
    - redis
  
  # À corriger :
  # les nouvelles données ne sont pas récupéré et donc perdu après un nouveau up ou build.
  redis:
    image: redis:latest
    # command: redis-server
    volumes:
    - ./redis/dump.rdb:/data/dump.rdb
